### ISSUE TITLE
npm-test.yml should also run on any push to `main`

### ISSUE THREAD

**Issue by seveibar** [seamapi/seam-plop#11]
Adjust template to run tests on any push to main

**Comment by andrii-balitskyi** [comment]
like so? 

![Image](https://user-images.githubusercontent.com/84702959/181260376-008eeb11-9b6f-4fee-8fad-0dcf9bd9f343.png)

**Comment by codetheweb** [comment]
I'm not sure if this is the desired behavior; but in workflows that don't need to ever fetch details from a pull request context I usually just do `on: push` to run on every push.

**Comment by andrii-balitskyi** [comment]
https://github.com/seamapi/seam-plop/pull/16
